//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDoradczy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemDoradczy.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like sci-fi or supernatural shows ?
        /// </summary>
        internal static string ScifiShowQuestion
        {
            get {
                return ResourceManager.GetString("ScifiShowQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Politics ?
        /// </summary>
        internal static string PoliticsQuestion
        {
            get {
                return ResourceManager.GetString("PoliticsQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can you handle Gore ?.
        /// </summary>
        internal static string GoreQuestion
        {
            get {
                return ResourceManager.GetString("GoreQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like strong female characters ?
        /// </summary>
        internal static string StrongFemaleQuestion
        {
            get {
                return ResourceManager.GetString("StrongFemaleQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Small town or prison ?
        /// </summary>
        internal static string TownOrPrisonQuestion
        {
            get {
                return ResourceManager.GetString("TownOrPrisonQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Glimore Girls.
        /// </summary>
        internal static string GilmoreGirlsAnswer
        {
            get {
                return ResourceManager.GetString("GilmoreGirlsAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friend group or dysfunctional family ?
        /// </summary>
        internal static string FriendOrFamilyQuestion
        {
            get {
                return ResourceManager.GetString("FriendOrFamilyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama or Comedy?.
        /// </summary>
        internal static string DramaOrComedy {
            get {
                return ResourceManager.GetString("DramaOrComedy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Orange Is the New Black.
        /// </summary>
        internal static string OitnbAnswer
        {
            get {
                return ResourceManager.GetString("OitnbAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to British Characters ?
        /// </summary>
        internal static string BritishCharQuestion
        {
            get {
                return ResourceManager.GetString("BritishCharQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feel like crying ?
        /// </summary>
        internal static string CryingQuestion
        {
            get {
                return ResourceManager.GetString("CryingQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: It's always sunny in Philadelphia.
        /// </summary>
        internal static string PhiladelphiaAnswer
        {
            get {
                return ResourceManager.GetString("PhiladelphiaAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Arrested Development.
        /// </summary>
        internal static string ArrestedAnswer
        {
            get {
                return ResourceManager.GetString("ArrestedAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like them tto sell drugs ?
        /// </summary>
        internal static string DrugsQuestion
        {
            get {
                return ResourceManager.GetString("DrugsQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Need action ?
        /// </summary>
        internal static string ActionQuestion
        {
            get {
                return ResourceManager.GetString("ActionQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work place humor ?
        /// </summary>
        internal static string WorkPlaceQuestion
        {
            get {
                return ResourceManager.GetString("WorkPlaceQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: The Office.
        /// </summary>
        internal static string TheOfficeAnswer
        {
            get {
                return ResourceManager.GetString("TheOfficeAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like football ?
        /// </summary>
        internal static string FootballQuestion
        {
            get {
                return ResourceManager.GetString("FootballQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Lost.
        /// </summary>
        internal static string LostAnswer
        {
            get {
                return ResourceManager.GetString("LostAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: 24.
        /// </summary>
        internal static string S24Answer {
            get {
                return ResourceManager.GetString("S24Answer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Dr.Who.
        /// </summary>
        internal static string DrWhoAnswer
        {
            get {
                return ResourceManager.GetString("DrWhoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: Weeds.
        /// </summary>
        internal static string WeedsAnswer
        {
            get {
                return ResourceManager.GetString("WeedsAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like crime shows ?
        /// </summary>
        internal static string CrimeQuestion
        {
            get {
                return ResourceManager.GetString("CrimeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w systemie doradczym pomgającym wybrać rodzaj pracy protetycznej.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like zombies ?
        /// </summary>
        internal static string ZombiesQuestion
        {
            get {
                return ResourceManager.GetString("ZombiesQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scandalous romance ?
        /// </summary>
        internal static string RomanceQuestion
        {
            get {
                return ResourceManager.GetString("RomanceQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you like your characters to have questionable morals ?.
        /// </summary>
        internal static string QuestionableMoralsQuestion
        {
            get
            {
                return ResourceManager.GetString("QuestionableMoralsQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hospitals ?
        /// </summary>

        internal static string HospitalsQuestion
        {
            get
            {
                return ResourceManager.GetString("HospitalsQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tina Fey or Amy Poehler ?
        /// </summary>

        internal static string TinaOrAmyQuestion
        {
            get
            {
                return ResourceManager.GetString("TinaOrAmyQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you root for the criminals ?
        /// </summary>

        internal static string CriminalsQuestion
        {
            get
            {
                return ResourceManager.GetString("CriminalsQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Friday Night Lights.
        /// </summary>

        internal static string FridayAnswer
        {
            get
            {
                return ResourceManager.GetString("FridayAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title: Parks and Recreation.
        /// </summary>

        internal static string ParksAnswer
        {
            get
            {
                return ResourceManager.GetString("ParksAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Title: 30 Rock.
        /// </summary>

        internal static string S30RockAnswer
        {
            get
            {
                return ResourceManager.GetString("S30RockAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Meth ? ( ͡° ͜ʖ ͡°).
        /// </summary>

        internal static string MethQuestion
        {
            get
            {
                return ResourceManager.GetString("MethQuestion", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to  Title: Breaking Bad.
        /// </summary>

        internal static string BreakingBadAnswer
        {
            get
            {
                return ResourceManager.GetString("BreakingBadAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Title: Scandal.
        /// </summary>

        internal static string ScandalAnswer
        {
            get
            {
                return ResourceManager.GetString("ScandalAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: Parenthood.
        /// </summary>

        internal static string ParenthoodAnswer
        {
            get
            {
                return ResourceManager.GetString("ParenthoodAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Title: Grey's Anatomy.
        /// </summary>

        internal static string AnatomyAnswer
        {
            get
            {
                return ResourceManager.GetString("AnatomyAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Optimistic or cynical ?
        /// </summary>


        internal static string OptimisticOrCynicalQuestion
        {
            get
            {
                return ResourceManager.GetString("OptimisticOrCynicalQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: The Walking Dead.
        /// </summary>


        internal static string DeadAnswer
        {
            get
            {
                return ResourceManager.GetString("DeadAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Vampires ?
        /// </summary>


        internal static string VampiresQuestion
        {
            get
            {
                return ResourceManager.GetString("VampiresQuestion", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Title: Freaks and Geeks.
        /// </summary>


        internal static string FreaksAnswer
        {
            get
            {
                return ResourceManager.GetString("FreaksAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: Mad Men.
        /// </summary>


        internal static string MadMenAnswer
        {
            get
            {
                return ResourceManager.GetString("MadMenAnswer", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to  Title: Dexter.
        /// </summary>


        internal static string DexterAnswer
        {
            get
            {
                return ResourceManager.GetString("DexterAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  IDK.
        /// </summary>


        internal static string IDKAnswer
        {
            get
            {
                return ResourceManager.GetString("IDKAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Do you want NYC friends to hang out at a bar or cafe ?
        /// </summary>


        internal static string BarOrCafeQuestion
        {
            get
            {
                return ResourceManager.GetString("BarOrCafeQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: Supernatural.
        /// </summary>


        internal static string SuperAnswer
        {
            get
            {
                return ResourceManager.GetString("SuperAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Forensics or psychology ?
        /// </summary>


        internal static string ForOrPsyQuestion
        {
            get
            {
                return ResourceManager.GetString("ForOrPsyQuestion", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Title: The Vampire Diaries.
        /// </summary>


        internal static string VampireAnswer
        {
            get
            {
                return ResourceManager.GetString("VampireAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: CSI: Miami.
        /// </summary>


        internal static string CSIAnswer
        {
            get
            {
                return ResourceManager.GetString("CSIAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: The West Wing.
        /// </summary>


        internal static string WestAnswer
        {
            get
            {
                return ResourceManager.GetString("WestAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: Criminal Minds.
        /// </summary>


        internal static string MindsAnswer
        {
            get
            {
                return ResourceManager.GetString("MindsAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: How i met your Mother ( ͡° ͜ʖ ͡°).
        /// </summary>


        internal static string MotherAnswer
        {
            get
            {
                return ResourceManager.GetString("MotherAnswer", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to  Title: Friends.
        /// </summary>


        internal static string FriendsAnswer
        {
            get
            {
                return ResourceManager.GetString("FriendsAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Title: House of Cards.
        /// </summary>


        internal static string HouseAnswer
        {
            get
            {
                return ResourceManager.GetString("HouseAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Want to see James Franco and Seth Rogen as High Schoolers ?
        /// </summary>
        internal static string WantToSeeQuestion
        {
            get {
                return ResourceManager.GetString("WantToSeeQuestion", resourceCulture);
            }
        }
    }
}
